In [43]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\devan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\devan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\devan\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\devan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\devan\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [44]:
import pandas as pd
df=pd.read_csv("exam_scores.csv")
df

,StudyHoursPerDay,AttendancePercentage,PreviousScore,SleepHours,PracticeTestsTaken,InternetAccess,FinalScore
0,4.058131,85.361932,42.471376,5.703021,2,1,57.717515
1,9.531786,57.626952,51.019152,4.358559,12,1,92.368020
2,7.453942,78.814418,44.732666,6.048144,2,1,71.572450
3,6.187256,80.335752,53.074760,5.556087,6,0,67.892677
4,1.982177,71.206534,34.512550,7.385603,5,0,42.920466
...,...,...,...,...,...,...,...
795,8.785177,78.919346,52.482035,6.528171,0,0,72.819146
796,9.355124,63.708033,40.039884,8.705604,14,1,89.023878
797,5.868765,53.970968,31.654104,8.381597,12,0,77.274683
798,7.118183,54.282912,71.978455,4.512840,0,1,49.813750
799,9.263744,94.709544,71.398651,5.963654,7,0,91.228477

In [45]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   StudyHoursPerDay      800 non-null    float64
 1   AttendancePercentage  800 non-null    float64
 2   PreviousScore         800 non-null    float64
 3   SleepHours            800 non-null    float64
 4   PracticeTestsTaken    800 non-null    int64
 5   InternetAccess        800 non-null    int64
 6   FinalScore            800 non-null    float64
dtypes: float64(5), int64(2)
memory usage: 43.9 KB

In [46]:
df.isnull().sum()

StudyHoursPerDay        0
AttendancePercentage    0
PreviousScore           0
SleepHours              0
PracticeTestsTaken      0
InternetAccess          0
FinalScore              0
dtype: int64

In [47]:
df.describe()

,StudyHoursPerDay,AttendancePercentage,PreviousScore,SleepHours,PracticeTestsTaken,InternetAccess,FinalScore
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000
mean,5.221085,75.005952,62.427982,6.502049,7.370000,0.505000,70.341763
std,2.789265,14.645756,18.680746,1.455925,4.368003,0.500288,15.747330
min,0.548085,50.231601,30.101732,4.000058,0.000000,0.000000,26.540899
25%,2.793543,61.771989,46.500506,5.327593,4.000000,0.000000,58.846708
50%,5.314121,75.235745,63.077937,6.475182,7.000000,1.000000,70.376425
75%,7.659859,86.975677,78.510711,7.771262,11.000000,1.000000,82.311480
max,9.997318,99.970686,94.892588,8.989104,14.000000,1.000000,100.000000

In [48]:
df.duplicated().sum()

np.int64(0)

In [49]:
df.drop_duplicates(inplace=True)

In [50]:
x=df.drop(['FinalScore'],axis=1)

In [51]:
y=df['FinalScore']
y

0      57.717515
1      92.368020
2      71.572450
3      67.892677
4      42.920466
         ...
795    72.819146
796    89.023878
797    77.274683
798    49.813750
799    91.228477
Name: FinalScore, Length: 800, dtype: float64

In [52]:
from sklearn.model_selection import train_test_split

In [53]:
x_train,x_test,y_train,y_test=train_test_split(x,
                                               y,
                                               test_size=0.2,
                                               random_state=42
                                               )

In [54]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [55]:
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.8730972775029249

In [60]:
import pickle
with open('exam_scores.pkl','wb') as f:
    pickle.dump(model,f)